// Country flag emoji mapping for all FIFA teams
export const countryFlags: { [key: string]: string } = {
  // Europe
  'Albania': '🇦🇱',
  'Andorra': '🇦🇩',
  'Armenia': '🇦🇲',
  'Austria': '🇦🇹',
  'Azerbaijan': '🇦🇿',
  'Belarus': '🇧🇾',
  'Belgium': '🇧🇪',
  'Bosnia and Herzegovina': '🇧🇦',
  'Bulgaria': '🇧🇬',
  'Croatia': '🇭🇷',
  'Cyprus': '🇨🇾',
  'Czech Republic': '🇨🇿',
  'Denmark': '🇩🇰',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Estonia': '🇪🇪',
  'Faroe Islands': '🇫🇴',
  'Finland': '🇫🇮',
  'France': '🇫🇷',
  'Georgia': '🇬🇪',
  'Germany': '🇩🇪',
  'Gibraltar': '🇬🇮',
  'Greece': '🇬🇷',
  'Hungary': '🇭🇺',
  'Iceland': '🇮🇸',
  'Ireland': '🇮🇪',
  'Israel': '🇮🇱',
  'Italy': '🇮🇹',
  'Kazakhstan': '🇰🇿',
  'Kosovo': '🇽🇰',
  'Latvia': '🇱🇻',
  'Liechtenstein': '🇱🇮',
  'Lithuania': '🇱🇹',
  'Luxembourg': '🇱🇺',
  'Malta': '🇲🇹',
  'Moldova': '🇲🇩',
  'Montenegro': '🇲🇪',
  'Netherlands': '🇳🇱',
  'North Macedonia': '🇲🇰',
  'Northern Ireland': '🇬🇧',
  'Norway': '🇳🇴',
  'Poland': '🇵🇱',
  'Portugal': '🇵🇹',
  'Romania': '🇷🇴',
  'Russia': '🇷🇺',
  'San Marino': '🇸🇲',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Serbia': '🇷🇸',
  'Slovakia': '🇸🇰',
  'Slovenia': '🇸🇮',
  'Spain': '🇪🇸',
  'Sweden': '🇸🇪',
  'Switzerland': '🇨🇭',
  'Turkey': '🇹🇷',
  'Ukraine': '🇺🇦',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  
  // South America
  'Argentina': '🇦🇷',
  'Bolivia': '🇧🇴',
  'Brazil': '🇧🇷',
  'Chile': '🇨🇱',
  'Colombia': '🇨🇴',
  'Ecuador': '🇪🇨',
  'Paraguay': '🇵🇾',
  'Peru': '🇵🇪',
  'Uruguay': '🇺🇾',
  'Venezuela': '🇻🇪',
  
  // North America & Caribbean
  'Antigua and Barbuda': '🇦🇬',
  'Aruba': '🇦🇼',
  'Bahamas': '🇧🇸',
  'Barbados': '🇧🇧',
  'Belize': '🇧🇿',
  'Bermuda': '🇧🇲',
  'Canada': '🇨🇦',
  'Cayman Islands': '🇰🇾',
  'Costa Rica': '🇨🇷',
  'Cuba': '🇨🇺',
  'Curaçao': '🇨🇼',
  'Dominica': '🇩🇲',
  'Dominican Republic': '🇩🇴',
  'El Salvador': '🇸🇻',
  'Grenada': '🇬🇩',
  'Guatemala': '🇬🇹',
  'Guyana': '🇬🇾',
  'Haiti': '🇭🇹',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'Mexico': '🇲🇽',
  'Montserrat': '🇲🇸',
  'Nicaragua': '🇳🇮',
  'Panama': '🇵🇦',
  'Puerto Rico': '🇵🇷',
  'Saint Kitts and Nevis': '🇰🇳',
  'Saint Lucia': '🇱🇨',
  'Saint Vincent and the Grenadines': '🇻🇨',
  'Suriname': '🇸🇷',
  'Trinidad and Tobago': '🇹🇹',
  'Turks and Caicos Islands': '🇹🇨',
  'United States': '🇺🇸',
  'US Virgin Islands': '🇻🇮',
  
  // Africa
  'Algeria': '🇩🇿',
  'Angola': '🇦🇴',
  'Benin': '🇧🇯',
  'Botswana': '🇧🇼',
  'Burkina Faso': '🇧🇫',
  'Burundi': '🇧🇮',
  'Cameroon': '🇨🇲',
  'Cape Verde': '🇨🇻',
  'Central African Republic': '🇨🇫',
  'Chad': '🇹🇩',
  'Comoros': '🇰🇲',
  'Congo': '🇨🇬',
  'Congo DR': '🇨🇩',
  'Djibouti': '🇩🇯',
  'Egypt': '🇪🇬',
  'Equatorial Guinea': '🇬🇶',
  'Eritrea': '🇪🇷',
  'Eswatini': '🇸🇿',
  'Ethiopia': '🇪🇹',
  'Gabon': '🇬🇦',
  'Gambia': '🇬🇲',
  'Ghana': '🇬🇭',
  'Guinea': '🇬🇳',
  'Guinea-Bissau': '🇬🇼',
  'Ivory Coast': '🇨🇮',
  'Kenya': '🇰🇪',
  'Lesotho': '🇱🇸',
  'Liberia': '🇱🇷',
  'Libya': '🇱🇾',
  'Madagascar': '🇲🇬',
  'Malawi': '🇲🇼',
  'Mali': '🇲🇱',
  'Mauritania': '🇲🇷',
  'Mauritius': '🇲🇺',
  'Morocco': '🇲🇦',
  'Mozambique': '🇲🇿',
  'Namibia': '🇳🇦',
  'Niger': '🇳🇪',
  'Nigeria': '🇳🇬',
  'Rwanda': '🇷🇼',
  'São Tomé and Príncipe': '🇸🇹',
  'Senegal': '🇸🇳',
  'Seychelles': '🇸🇨',
  'Sierra Leone': '🇸🇱',
  'Somalia': '🇸🇴',
  'South Africa': '🇿🇦',
  'South Sudan': '🇸🇸',
  'Sudan': '🇸🇩',
  'Tanzania': '🇹🇿',
  'Togo': '🇹🇬',
  'Tunisia': '🇹🇳',
  'Uganda': '🇺🇬',
  'Zambia': '🇿🇲',
  'Zimbabwe': '🇿🇼',
  
  // Asia
  'Afghanistan': '🇦🇫',
  'Australia': '🇦🇺',
  'Bahrain': '🇧🇭',
  'Bangladesh': '🇧🇩',
  'Bhutan': '🇧🇹',
  'Brunei': '🇧🇳',
  'Cambodia': '🇰🇭',
  'China': '🇨🇳',
  'Chinese Taipei': '🇹🇼',
  'Guam': '🇬🇺',
  'Hong Kong': '🇭🇰',
  'India': '🇮🇳',
  'Indonesia': '🇮🇩',
  'Iran': '🇮🇷',
  'Iraq': '🇮🇶',
  'Japan': '🇯🇵',
  'Jordan': '🇯🇴',
  'Kuwait': '🇰🇼',
  'Kyrgyzstan': '🇰🇬',
  'Laos': '🇱🇦',
  'Lebanon': '🇱🇧',
  'Macao': '🇲🇴',
  'Malaysia': '🇲🇾',
  'Maldives': '🇲🇻',
  'Mongolia': '🇲🇳',
  'Myanmar': '🇲🇲',
  'Nepal': '🇳🇵',
  'North Korea': '🇰🇵',
  'Oman': '🇴🇲',
  'Pakistan': '🇵🇰',
  'Palestine': '🇵🇸',
  'Philippines': '🇵🇭',
  'Qatar': '🇶🇦',
  'Saudi Arabia': '🇸🇦',
  'Singapore': '🇸🇬',
  'South Korea': '🇰🇷',
  'Sri Lanka': '🇱🇰',
  'Syria': '🇸🇾',
  'Tajikistan': '🇹🇯',
  'Thailand': '🇹🇭',
  'Timor-Leste': '🇹🇱',
  'Turkmenistan': '🇹🇲',
  'United Arab Emirates': '🇦🇪',
  'Uzbekistan': '🇺🇿',
  'Vietnam': '🇻🇳',
  'Yemen': '🇾🇪',
  
  // Oceania
  'American Samoa': '🇦🇸',
  'Cook Islands': '🇨🇰',
  'Fiji': '🇫🇯',
  'New Caledonia': '🇳🇨',
  'New Zealand': '🇳🇿',
  'Papua New Guinea': '🇵🇬',
  'Samoa': '🇼🇸',
  'Solomon Islands': '🇸🇧',
  'Tahiti': '🇵🇫',
  'Tonga': '🇹🇴',
  'Vanuatu': '🇻🇺',
}

export const getCountryFlag = (countryName: string): string => {
  return countryFlags[countryName] || '🏳️'
}